const cfg=window.TNYPL_CONFIG;const sb=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);let players=[];
const $=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
async function checkSession(){const{data}=await sb.auth.getSession();data.session?showDashboard():showLogin()}
function showLogin(){$("loginPanel").hidden=false;$("dashboard").hidden=true}
async function showDashboard(){$("loginPanel").hidden=true;$("dashboard").hidden=false;await Promise.all([loadPlayers(),loadStatus()])}
$("loginForm").onsubmit=async e=>{e.preventDefault();const{error}=await sb.auth.signInWithPassword({email:$("adminEmail").value,password:$("adminPassword").value});$("loginMessage").textContent=error?error.message:"";if(!error)showDashboard()}
$("logoutBtn").onclick=async()=>{await sb.auth.signOut();showLogin()}
async function loadStatus(){const{data}=await sb.from("league_settings").select("value").eq("key","league_status").maybeSingle();if(data)$("leagueStatus").value=data.value}
$("saveLeagueStatus").onclick=async()=>{await sb.from("league_settings").upsert({key:"league_status",value:$("leagueStatus").value});alert("League status updated.");}
async function loadPlayers(){const{data,error}=await sb.from("players").select("*").order("created_at",{ascending:false});if(error){alert(error.message);return}players=data||[];renderStats();renderTable()}
function renderStats(){$("totalCount").textContent=players.length;$("pendingCount").textContent=players.filter(p=>(p.status||"pending")==="pending").length;$("verifiedCount").textContent=players.filter(p=>["verified","approved"].includes(p.status)).length;$("eligibleCount").textContent=players.filter(p=>p.draft_status==="draft_eligible").length;$("draftedCountAdmin").textContent=players.filter(p=>p.draft_status==="drafted").length;$("refundCount").textContent=players.filter(p=>p.refund_status==="eligible").length}
function filtered(){const q=$("searchInput").value.toLowerCase(),s=$("statusFilter").value,c=$("categoryFilter").value;return players.filter(p=>(!s||p.status===s)&&(!c||p.draft_category===c)&&(`${p.full_name} ${p.district} ${p.primary_role} ${p.registration_reference}`.toLowerCase().includes(q)))}
function docLink(path,label){return path?`<button onclick="openPrivate('${esc(path)}')">${label}</button>`:"—"}
function renderTable(){$("playersBody").innerHTML=filtered().map(p=>`<tr><td><strong>${esc(p.full_name)}</strong><br><small>${esc(p.registration_reference||"")}</small><br><small>${esc(p.email||"")}</small></td><td>${p.profile_photo_public_url?`<img class="admin-player-photo" src="${esc(p.profile_photo_public_url)}">`:"—"}</td><td>${esc(p.date_of_birth)}<br>${esc(p.district)}</td><td>${esc(p.primary_role)}<br><small>${esc(p.batting_style||"")} · ${esc(p.bowling_style||"")}</small></td><td>${esc(p.payment_status||"pending")}<br>${docLink(p.payment_receipt_path,"Receipt")}</td><td>${esc(p.age_verification_status||"pending")}<br>${docLink(p.age_proof_path,"Age Proof")}</td><td><select onchange="setCategory('${p.id}',this.value)"><option value="">Unassigned</option><option value="platinum" ${p.draft_category==="platinum"?"selected":""}>Platinum</option><option value="gold" ${p.draft_category==="gold"?"selected":""}>Gold</option><option value="silver" ${p.draft_category==="silver"?"selected":""}>Silver</option></select><input class="points-input" type="number" value="${p.starting_points||0}" onchange="setPoints('${p.id}',this.value)"></td><td>${esc(p.draft_status||"not_eligible_yet")}<br><small>${esc(p.drafted_franchise||"")}</small></td><td class="action-stack"><button onclick="verify('${p.id}','payment_status')">Verify Payment</button><button onclick="verify('${p.id}','age_verification_status')">Verify Age</button><button onclick="setStatus('${p.id}','verified')">Approve</button><button onclick="setDraft('${p.id}','draft_eligible')">Draft Eligible</button><button onclick="requestChanges('${p.id}')">Request Changes</button><button onclick="setStatus('${p.id}','rejected')">Reject</button></td></tr>`).join("")}
window.openPrivate=async path=>{const{data,error}=await sb.storage.from("player-documents").createSignedUrl(path,300);if(error)alert(error.message);else window.open(data.signedUrl,"_blank")}
async function updatePlayer(id,patch,action){const current=players.find(p=>String(p.id)===String(id));const{error}=await sb.from("players").update(patch).eq("id",id);if(error){alert(error.message);return}await sb.from("player_audit_logs").insert({player_id:String(id),action,previous_value:current,new_value:patch,notes:"Updated from Admin Portal"});await queueStatusEmail(id,action);await loadPlayers()}
async function queueStatusEmail(id,action){const p=players.find(x=>String(x.id)===String(id));if(!p?.email)return;await sb.from("email_queue").insert({player_id:String(id),recipient_email:p.email,template_key:action,status:"pending",payload:{player_name:p.full_name,registration_reference:p.registration_reference,franchise:p.drafted_franchise}})}
window.verify=(id,field)=>updatePlayer(id,{[field]:"verified"},field+"_verified")
window.setStatus=(id,status)=>updatePlayer(id,{status,verified_at:status==="verified"?new Date().toISOString():null},status)
window.setDraft=(id,status)=>{const p=players.find(x=>String(x.id)===String(id));if(status==="draft_eligible"&&(p.payment_status!=="verified"||p.age_verification_status!=="verified"))return alert("Payment and age proof must be verified first.");return updatePlayer(id,{draft_status:status},"draft_status_"+status)}
window.setCategory=(id,value)=>updatePlayer(id,{draft_category:value||null},"category_assigned")
window.setPoints=(id,value)=>updatePlayer(id,{starting_points:Number(value||0)},"starting_points_updated")
window.requestChanges=id=>{const note=prompt("What should the player correct?");if(note)updatePlayer(id,{status:"changes_requested",correction_notes:note},"changes_requested")}
$("searchInput").oninput=renderTable;$("statusFilter").onchange=renderTable;$("categoryFilter").onchange=renderTable;
function exportCsv(rows,name){const cols=["registration_reference","full_name","date_of_birth","district","primary_role","batting_style","bowling_style","academy","cricheroes_url","draft_category","starting_points","status","draft_status","drafted_franchise"];const q=v=>`"${String(v??"").replaceAll('"','""')}"`;const csv=[cols.join(","),...rows.map(p=>cols.map(c=>q(p[c])).join(","))].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=name;a.click()}
$("exportBtn").onclick=()=>exportCsv(players,"tnypl-player-master-list.csv");$("draftExportBtn").onclick=()=>exportCsv(players.filter(p=>p.draft_status==="draft_eligible"),"tnypl-official-draft-pool.csv");
checkSession();