const cfg=window.TNYPL_CONFIG;
const sb=window.supabase?supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
document.getElementById('menuToggle')?.addEventListener('click',()=>document.getElementById('navLinks')?.classList.toggle('open'));

function tzParts(date,tz){const f=new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit'});return Object.fromEntries(f.formatToParts(date).filter(x=>x.type!=='literal').map(x=>[x.type,Number(x.value)]))}
function countdown(){const e=document.getElementById('countDays');if(!e)return;const n=tzParts(new Date(),cfg.TOURNAMENT_TIMEZONE||'Asia/Kolkata');const [y,m,d]=(cfg.TOURNAMENT_DATE||'2026-09-14').split('-').map(Number);e.textContent=Math.max(0,Math.ceil((Date.UTC(y,m-1,d)-Date.UTC(n.year,n.month-1,n.day))/86400000))}
countdown();setInterval(countdown,60000);

const tabs=[...document.querySelectorAll('.step-tab')],panels=[...document.querySelectorAll('.form-step')];let current=1;
function showStep(n){current=Math.max(1,Math.min(4,n));tabs.forEach(t=>t.classList.toggle('active',+t.dataset.step===current));panels.forEach(p=>p.classList.toggle('active',+p.dataset.stepPanel===current))}
tabs.forEach(t=>t.addEventListener('click',()=>showStep(+t.dataset.step)));document.querySelectorAll('.next-step').forEach(b=>b.addEventListener('click',()=>showStep(current+1)));document.querySelectorAll('.prev-step').forEach(b=>b.addEventListener('click',()=>showStep(current-1)));

const dob=document.getElementById('dob'),ageDisplay=document.getElementById('ageDisplay');
if(dob){dob.min=cfg.MIN_DOB||'2010-01-01';dob.max=cfg.MAX_DOB||'2012-12-31';dob.addEventListener('change',()=>{if(!dob.value)return ageDisplay.value='';const b=new Date(dob.value+'T00:00:00'),r=new Date('2026-09-14T00:00:00');let y=r.getFullYear()-b.getFullYear(),m=r.getMonth()-b.getMonth(),d=r.getDate()-b.getDate();if(d<0){m--;d+=new Date(r.getFullYear(),r.getMonth(),0).getDate()}if(m<0){y--;m+=12}ageDisplay.value=`${y} years, ${m} months, ${d} days`})}
async function upload(file,folder){const path=`${folder}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const {error}=await sb.storage.from('player-documents').upload(path,file);if(error)throw error;return path}
document.getElementById('registrationForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,msg=document.getElementById('formMessage'),btn=f.querySelector('[type=submit]');btn.disabled=true;msg.textContent='Submitting...';try{if(!sb)throw new Error('Registration service unavailable');if(dob.value<(cfg.MIN_DOB||'2010-01-01')||dob.value>(cfg.MAX_DOB||'2012-12-31'))throw new Error('DOB must be between 01 January 2010 and 31 December 2012.');const data=new FormData(f);const [agePath,payPath]=await Promise.all([upload(document.getElementById('ageProof').files[0],'age-proofs'),upload(document.getElementById('paymentReceipt').files[0],'payment-receipts')]);const payload={full_name:data.get('full_name'),date_of_birth:data.get('date_of_birth'),district:data.get('district'),parent_name:data.get('parent_name'),parent_phone:data.get('parent_phone'),email:data.get('email'),school:data.get('school'),academy:data.get('academy'),cricheroes_url:data.get('cricheroes_url'),primary_role:data.get('primary_role'),batting_style:data.get('batting_style'),bowling_style:data.get('bowling_style'),tshirt_size:data.get('tshirt_size'),pant_size:data.get('pant_size'),age_proof_path:agePath,payment_receipt_path:payPath,status:'pending'};const {error}=await sb.from('players').insert(payload);if(error)throw error;f.reset();showStep(1);msg.textContent='Registration received. Verification is pending.';msg.style.color='#6ee7b7'}catch(err){msg.textContent=err.message;msg.style.color='#fca5a5'}finally{btn.disabled=false}});
