-- ============================================================
-- TNYPL V11.1 COMPLETE SUPABASE SETUP
-- Run once in Supabase > SQL Editor.
-- Review the comments before running in production.
-- ============================================================

create extension if not exists pgcrypto;

-- ------------------------------------------------------------
-- 1. Ensure the player table has the operational status fields.
-- ------------------------------------------------------------
alter table if exists public.players
  add column if not exists payment_status text not null default 'pending',
  add column if not exists age_verification_status text not null default 'pending',
  add column if not exists draft_status text not null default 'not_eligible_yet',
  add column if not exists refund_status text not null default 'not_applicable',
  add column if not exists privacy_consent_at timestamptz,
  add column if not exists guardian_consent_at timestamptz,
  add column if not exists verified_at timestamptz,
  add column if not exists verified_by uuid,
  add column if not exists rejection_reason text,
  add column if not exists registration_reference text;

-- Fill a reference for existing rows when an id column is available.
do $block$
begin
  if to_regclass('public.players') is not null
     and exists (
       select 1 from information_schema.columns
       where table_schema='public' and table_name='players' and column_name='id'
     ) then
    execute $sql$
      update public.players
      set registration_reference =
        'TNYPL-' || to_char(coalesce(created_at, now()), 'YYYYMMDD') || '-' ||
        upper(substr(md5(id::text || coalesce(email,'')),1,6))
      where registration_reference is null
    $sql$;
  end if;
end
$block$;

-- ------------------------------------------------------------
-- 2. Audit history for verification, draft and refund actions.
-- ------------------------------------------------------------
create table if not exists public.player_audit_logs (
  id bigint generated by default as identity primary key,
  player_id text not null,
  action text not null,
  previous_value jsonb,
  new_value jsonb,
  notes text,
  acted_by uuid,
  created_at timestamptz not null default now()
);

create index if not exists player_audit_logs_player_idx
  on public.player_audit_logs(player_id);

create index if not exists player_audit_logs_created_idx
  on public.player_audit_logs(created_at desc);

alter table public.player_audit_logs enable row level security;
revoke all on public.player_audit_logs from anon;

drop policy if exists "Admins read audit logs" on public.player_audit_logs;
create policy "Admins read audit logs"
on public.player_audit_logs
for select
to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Admins create audit logs" on public.player_audit_logs;
create policy "Admins create audit logs"
on public.player_audit_logs
for insert
to authenticated
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- ------------------------------------------------------------
-- 3. Private document-storage bucket.
-- ------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'player-documents',
  'player-documents',
  false,
  10485760,
  array['image/jpeg','image/png','application/pdf']
)
on conflict (id) do update
set public=false,
    file_size_limit=excluded.file_size_limit,
    allowed_mime_types=excluded.allowed_mime_types;

-- Applicants can upload, but cannot list or download private documents.
drop policy if exists "Applicants upload player documents" on storage.objects;
create policy "Applicants upload player documents"
on storage.objects
for insert
to anon, authenticated
with check (
  bucket_id='player-documents'
  and (storage.foldername(name))[1] in ('age-proofs','payment-receipts')
);

-- Only authenticated admins can view or remove private documents.
drop policy if exists "Admins read player documents" on storage.objects;
create policy "Admins read player documents"
on storage.objects
for select
to authenticated
using (
  bucket_id='player-documents'
  and (auth.jwt() -> 'app_metadata' ->> 'role')='admin'
);

drop policy if exists "Admins delete player documents" on storage.objects;
create policy "Admins delete player documents"
on storage.objects
for delete
to authenticated
using (
  bucket_id='player-documents'
  and (auth.jwt() -> 'app_metadata' ->> 'role')='admin'
);

-- ------------------------------------------------------------
-- 4. Real visitor and country analytics.
-- Netlify Functions call these with the service-role key.
-- ------------------------------------------------------------
create table if not exists public.site_visitors (
  visitor_id text primary key,
  country_code text not null default 'XX',
  country_name text not null default 'Unknown',
  city text,
  first_seen timestamptz not null default now(),
  last_seen timestamptz not null default now()
);

create table if not exists public.site_page_views (
  id bigint generated by default as identity primary key,
  visitor_id text not null,
  page_path text not null default '/',
  country_code text not null default 'XX',
  viewed_at timestamptz not null default now()
);

create index if not exists site_visitors_last_seen_idx
  on public.site_visitors(last_seen desc);

create index if not exists site_page_views_viewed_idx
  on public.site_page_views(viewed_at desc);

alter table public.site_visitors enable row level security;
alter table public.site_page_views enable row level security;
revoke all on public.site_visitors from anon, authenticated;
revoke all on public.site_page_views from anon, authenticated;

create or replace function public.track_site_visit_v11(
  p_visitor_id text,
  p_country_code text default 'XX',
  p_country_name text default 'Unknown',
  p_city text default null,
  p_page_path text default '/'
)
returns void
language plpgsql
security definer
set search_path=public
as $fn$
begin
  if p_visitor_id is null
     or length(p_visitor_id)<8
     or length(p_visitor_id)>120 then
    raise exception 'Invalid visitor identifier';
  end if;

  insert into public.site_visitors(
    visitor_id,country_code,country_name,city,first_seen,last_seen
  )
  values(
    p_visitor_id,
    upper(coalesce(nullif(p_country_code,''),'XX')),
    left(coalesce(nullif(p_country_name,''),'Unknown'),120),
    left(nullif(p_city,''),120),
    now(),
    now()
  )
  on conflict(visitor_id) do update
  set country_code=excluded.country_code,
      country_name=excluded.country_name,
      city=excluded.city,
      last_seen=now();

  insert into public.site_page_views(
    visitor_id,page_path,country_code,viewed_at
  )
  values(
    p_visitor_id,
    left(coalesce(nullif(p_page_path,''),'/'),300),
    upper(coalesce(nullif(p_country_code,''),'XX')),
    now()
  );
end
$fn$;

create or replace function public.get_public_site_stats_v11()
returns jsonb
language plpgsql
security definer
set search_path=public
as $fn$
declare
  v_registrations bigint:=0;
  v_verified bigint:=0;
  v_draft_eligible bigint:=0;
  v_drafted bigint:=0;
  v_refunds bigint:=0;
begin
  if to_regclass('public.players') is not null then
    execute 'select count(*) from public.players'
      into v_registrations;

    execute $sql$
      select count(*) from public.players
      where lower(coalesce(status,'')) in ('verified','approved')
         or lower(coalesce(age_verification_status,''))='verified'
    $sql$ into v_verified;

    execute $sql$
      select count(*) from public.players
      where lower(coalesce(draft_status,''))='draft_eligible'
    $sql$ into v_draft_eligible;

    execute $sql$
      select count(*) from public.players
      where lower(coalesce(draft_status,''))='drafted'
         or lower(coalesce(status,'')) in ('drafted','selected')
    $sql$ into v_drafted;

    execute $sql$
      select count(*) from public.players
      where lower(coalesce(refund_status,''))='paid'
         or lower(coalesce(payment_status,''))='refunded'
    $sql$ into v_refunds;
  end if;

  return jsonb_build_object(
    'unique_visitors',
      (select count(*) from public.site_visitors),

    'page_views',
      (select count(*) from public.site_page_views),

    'countries_reached',
      (select count(distinct country_code)
       from public.site_visitors
       where country_code<>'XX'),

    'online_now',
      (select count(*)
       from public.site_visitors
       where last_seen>=now()-interval '5 minutes'),

    'registrations',v_registrations,
    'verified_players',v_verified,
    'draft_eligible_players',v_draft_eligible,
    'drafted_players',v_drafted,
    'refunds_processed',v_refunds,

    'countries',
      coalesce((
        select jsonb_agg(
          jsonb_build_object(
            'country_code',country_code,
            'country_name',country_name,
            'visitors',visitors,
            'page_views',page_views
          )
          order by visitors desc
        )
        from (
          select
            v.country_code,
            max(v.country_name) as country_name,
            count(*) as visitors,
            (
              select count(*)
              from public.site_page_views pv
              where pv.country_code=v.country_code
            ) as page_views
          from public.site_visitors v
          where v.country_code<>'XX'
          group by v.country_code
          order by count(*) desc
          limit 10
        ) ranked
      ),'[]'::jsonb),

    'updated_at',now()
  );
end
$fn$;

revoke all on function public.track_site_visit_v11(text,text,text,text,text)
  from public;
revoke all on function public.get_public_site_stats_v11()
  from public;

-- ------------------------------------------------------------
-- 5. Registration verification query.
-- ------------------------------------------------------------
select
  full_name,
  email,
  status,
  payment_status,
  age_verification_status,
  draft_status,
  refund_status,
  registration_reference,
  created_at
from public.players
order by created_at desc
limit 20;

select public.get_public_site_stats_v11();
