-- TNYPL PREVIEW: PRIVATE DOCUMENTS, VERIFICATION AND AUDIT LOGS
-- Review in a staging Supabase project before production use.

-- Use one PRIVATE bucket. Create it from Storage as:
-- player-documents (Public bucket = OFF)

alter table public.players
  add column if not exists payment_status text not null default 'pending',
  add column if not exists age_verification_status text not null default 'pending',
  add column if not exists draft_status text not null default 'not_eligible_yet',
  add column if not exists refund_status text not null default 'not_applicable',
  add column if not exists verified_at timestamptz,
  add column if not exists verified_by uuid,
  add column if not exists privacy_consent_at timestamptz;

create table if not exists public.player_audit_logs (
  id bigint generated by default as identity primary key,
  player_id bigint,
  action text not null,
  previous_value jsonb,
  new_value jsonb,
  notes text,
  acted_by uuid,
  created_at timestamptz not null default now()
);

alter table public.player_audit_logs enable row level security;

-- No direct anonymous access to audit logs.
revoke all on table public.player_audit_logs from anon;

-- Storage policies: authenticated admins only.
-- Adapt the admin check to your profiles/admin_roles table before enabling.
-- Do NOT create a public SELECT policy on storage.objects for player-documents.

-- Example signed URL usage should happen only in an authenticated admin session:
-- supabase.storage.from('player-documents').createSignedUrl(path, 300)

-- Recommended statuses:
-- players.status: pending | changes_requested | verified | rejected
-- payment_status: pending | verified | failed | refunded
-- age_verification_status: pending | verified | failed
-- draft_status: not_eligible_yet | draft_eligible | drafted | not_drafted
-- refund_status: not_applicable | eligible | processing | paid

-- Verify latest registrations:
select full_name, email, status, payment_status, age_verification_status,
       draft_status, refund_status, created_at
from public.players
order by created_at desc
limit 20;
