
-- TNYPL ADMIN, ATTACHMENTS, DRAFT & EMAIL SETUP
-- Run this entire script in Supabase SQL Editor.

create extension if not exists pgcrypto;

-- Player registrations
create table if not exists public.players (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  full_name text not null,
  date_of_birth date not null,
  parent_name text not null,
  parent_phone text not null,
  email text not null,
  district text not null,
  school text,
  academy text,
  cricheroes_url text,
  primary_role text,
  batting_style text,
  bowling_style text,
  tshirt_size text,
  pant_size text,
  age_proof_path text,
  payment_receipt_path text,
  payment_verified boolean not null default false,
  age_verified boolean not null default false,
  status text not null default 'pending',
  drafted boolean not null default false,
  drafted_team text,
  drafted_at timestamptz,
  registration_email_sent_at timestamptz,
  drafted_email_sent_at timestamptz,
  admin_notes text
);

alter table public.players add column if not exists drafted boolean not null default false;
alter table public.players add column if not exists drafted_team text;
alter table public.players add column if not exists drafted_at timestamptz;
alter table public.players add column if not exists registration_email_sent_at timestamptz;
alter table public.players add column if not exists drafted_email_sent_at timestamptz;
alter table public.players add column if not exists admin_notes text;

-- Authorized administrators.
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  created_at timestamptz not null default now()
);

-- Email delivery audit.
create table if not exists public.email_log (
  id bigint generated by default as identity primary key,
  player_id uuid references public.players(id) on delete set null,
  email_type text not null,
  recipient text not null,
  provider_message_id text,
  status text not null,
  error_message text,
  created_at timestamptz not null default now()
);

-- Storage bucket for private player documents.
insert into storage.buckets (id, name, public)
values ('player-documents', 'player-documents', false)
on conflict (id) do update set public = false;

alter table public.players enable row level security;
alter table public.admin_users enable row level security;
alter table public.email_log enable row level security;

drop policy if exists "public can submit registrations" on public.players;
create policy "public can submit registrations"
on public.players for insert
to anon, authenticated
with check (
  status = 'pending'
  and drafted = false
  and payment_verified = false
  and age_verified = false
);

drop policy if exists "admins can read players" on public.players;
create policy "admins can read players"
on public.players for select
to authenticated
using (exists (
  select 1 from public.admin_users a where a.user_id = auth.uid()
));

drop policy if exists "admins can update players" on public.players;
create policy "admins can update players"
on public.players for update
to authenticated
using (exists (
  select 1 from public.admin_users a where a.user_id = auth.uid()
))
with check (exists (
  select 1 from public.admin_users a where a.user_id = auth.uid()
));

drop policy if exists "admins can view admin users" on public.admin_users;
create policy "admins can view admin users"
on public.admin_users for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "admins can read email log" on public.email_log;
create policy "admins can read email log"
on public.email_log for select
to authenticated
using (exists (
  select 1 from public.admin_users a where a.user_id = auth.uid()
));

-- Public upload is allowed only inside the expected registration folders.
drop policy if exists "public uploads player documents" on storage.objects;
create policy "public uploads player documents"
on storage.objects for insert
to anon, authenticated
with check (
  bucket_id = 'player-documents'
  and (
    name like 'age-proofs/%'
    or name like 'payment-receipts/%'
  )
);

drop policy if exists "admins read player documents" on storage.objects;
create policy "admins read player documents"
on storage.objects for select
to authenticated
using (
  bucket_id = 'player-documents'
  and exists (
    select 1 from public.admin_users a where a.user_id = auth.uid()
  )
);

-- Useful index for admin filtering.
create index if not exists players_status_idx on public.players(status);
create index if not exists players_drafted_idx on public.players(drafted);
create index if not exists players_created_at_idx on public.players(created_at desc);

-- After creating your admin in Authentication > Users, run:
-- insert into public.admin_users(user_id,email)
-- select id,email from auth.users where email='YOUR_ADMIN_EMAIL'
-- on conflict (user_id) do update set email=excluded.email;
