-- ============================================================
-- TNYPL V12 COMPLETE SUPABASE SETUP
-- Run in Supabase SQL Editor.
-- IMPORTANT: test in staging before public launch.
-- ============================================================

create extension if not exists pgcrypto;

-- Core league settings
create table if not exists public.league_settings(
  key text primary key,
  value text,
  updated_at timestamptz not null default now()
);
insert into public.league_settings(key,value) values
 ('league_status','Registration Open'),
 ('registration_open','true'),
 ('draft_date','2026-08-25T10:00:00+05:30'),
 ('tournament_start','2026-09-14T08:00:00+05:30'),
 ('tournament_end','2026-09-18T20:00:00+05:30'),
 ('official_email','info@tnypl.in'),
 ('youtube_channel_url','https://youtube.com/@tamilnaduyouthpremierleague'),
 ('live_match_id',''),
 ('live_youtube_url',''),
 ('live_youtube_video_id','')
on conflict(key) do nothing;

-- Players: assumes public.players already exists from the registration setup.
alter table if exists public.players
 add column if not exists registration_reference text,
 add column if not exists profile_photo_path text,
 add column if not exists profile_photo_public_url text,
 add column if not exists media_consent boolean not null default false,
 add column if not exists privacy_consent_at timestamptz,
 add column if not exists guardian_consent_at timestamptz,
 add column if not exists payment_status text not null default 'pending',
 add column if not exists age_verification_status text not null default 'pending',
 add column if not exists status text not null default 'pending',
 add column if not exists correction_notes text,
 add column if not exists draft_status text not null default 'not_eligible_yet',
 add column if not exists draft_category text check(draft_category in ('platinum','gold','silver')),
 add column if not exists evaluation_score numeric,
 add column if not exists starting_points integer not null default 0,
 add column if not exists current_bid integer,
 add column if not exists final_points integer,
 add column if not exists drafted_franchise text,
 add column if not exists draft_order integer,
 add column if not exists refund_status text not null default 'not_applicable',
 add column if not exists verified_at timestamptz,
 add column if not exists verified_by uuid;

create unique index if not exists players_registration_reference_idx on public.players(registration_reference) where registration_reference is not null;

-- Private age proof/payment storage.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('player-documents','player-documents',false,10485760,array['image/jpeg','image/png','application/pdf'])
on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

-- Public approved profile photos.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('player-profile-photos','player-profile-photos',true,5242880,array['image/jpeg','image/png'])
on conflict(id) do update set public=true,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "Applicants upload private documents" on storage.objects;
create policy "Applicants upload private documents" on storage.objects for insert to anon,authenticated
with check(bucket_id='player-documents' and (storage.foldername(name))[1] in ('age-proofs','payment-receipts'));

drop policy if exists "Applicants upload profile photos" on storage.objects;
create policy "Applicants upload profile photos" on storage.objects for insert to anon,authenticated
with check(bucket_id='player-profile-photos' and (storage.foldername(name))[1]='player-photos');

drop policy if exists "Public read profile photos" on storage.objects;
create policy "Public read profile photos" on storage.objects for select to public
using(bucket_id='player-profile-photos');

drop policy if exists "Admins read private documents" on storage.objects;
create policy "Admins read private documents" on storage.objects for select to authenticated
using(bucket_id='player-documents' and (auth.jwt()->'app_metadata'->>'role') in ('admin','super_admin','registration_admin','commissioner'));

-- Audit logs
create table if not exists public.player_audit_logs(
 id bigint generated by default as identity primary key,
 player_id text not null,
 action text not null,
 previous_value jsonb,
 new_value jsonb,
 notes text,
 acted_by uuid,
 created_at timestamptz not null default now()
);
alter table public.player_audit_logs enable row level security;

-- Owner assignments
create table if not exists public.franchise_owner_assignments(
 id bigint generated by default as identity primary key,
 user_id uuid not null unique references auth.users(id) on delete cascade,
 franchise_slug text not null unique,
 franchise_name text not null,
 owner_name text not null,
 is_active boolean not null default true,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
alter table public.franchise_owner_assignments enable row level security;
drop policy if exists "Owners read own assignment" on public.franchise_owner_assignments;
create policy "Owners read own assignment" on public.franchise_owner_assignments for select to authenticated using(user_id=auth.uid());

-- Known owner emails (create users in Authentication first).
insert into public.franchise_owner_assignments(user_id,franchise_slug,franchise_name,owner_name)
select id,'kovai-kings','Kovai Kings','Gopi Ramadoss' from auth.users where lower(email)=lower('Gopiramadoss@gmail.com')
on conflict(user_id) do update set franchise_slug=excluded.franchise_slug,franchise_name=excluded.franchise_name,owner_name=excluded.owner_name,is_active=true,updated_at=now();

insert into public.franchise_owner_assignments(user_id,franchise_slug,franchise_name,owner_name)
select id,'karaikudi-kings','Karaikudi Kings','Porkai Pandian Gopalakrishnan' from auth.users where lower(email)=lower('porkai@cakepoint.in')
on conflict(user_id) do update set franchise_slug=excluded.franchise_slug,franchise_name=excluded.franchise_name,owner_name=excluded.owner_name,is_active=true,updated_at=now();

insert into public.franchise_owner_assignments(user_id,franchise_slug,franchise_name,owner_name)
select id,'nellai-falcons','Nellai Falcons','Ramanathan Periyaraja' from auth.users where lower(email)=lower('rohan.ramanathan@gmail.com')
on conflict(user_id) do update set franchise_slug=excluded.franchise_slug,franchise_name=excluded.franchise_name,owner_name=excluded.owner_name,is_active=true,updated_at=now();

-- Franchises and budgets
create table if not exists public.franchises(
 slug text primary key,
 name text not null,
 owner_name text not null,
 starting_points integer not null default 1000,
 points_spent integer not null default 0,
 squad_limit integer not null default 13,
 is_active boolean not null default true
);
insert into public.franchises(slug,name,owner_name) values
 ('chennai-strikers','Chennai Strikers','Vimalesh Vedachalam'),
 ('kovai-kings','Kovai Kings','Gopi Ramadoss'),
 ('karaikudi-kings','Karaikudi Kings','Porkai Pandian Gopalakrishnan'),
 ('trichy-titans','Trichy Titans','Satish Raja'),
 ('nellai-falcons','Nellai Falcons','Ramanathan Periyaraja'),
 ('tiruppur-blazers','Tiruppur Blazers','P. C. Binny Jo')
on conflict(slug) do update set name=excluded.name,owner_name=excluded.owner_name;

create table if not exists public.draft_bids(
 id bigint generated by default as identity primary key,
 player_id text not null,
 franchise_slug text not null references public.franchises(slug),
 bid_points integer not null check(bid_points>0),
 bid_status text not null default 'active',
 created_by uuid,
 created_at timestamptz not null default now()
);
create table if not exists public.draft_picks(
 id bigint generated by default as identity primary key,
 pick_number integer not null unique,
 player_id text not null unique,
 franchise_slug text not null references public.franchises(slug),
 final_points integer not null,
 category text,
 selected_at timestamptz not null default now()
);

-- Email queue
create table if not exists public.email_queue(
 id bigint generated by default as identity primary key,
 player_id text,
 recipient_email text not null,
 template_key text not null,
 payload jsonb not null default '{}'::jsonb,
 status text not null default 'pending',
 last_error text,
 created_at timestamptz not null default now(),
 sent_at timestamptz
);

-- Notices/media
create table if not exists public.league_notices(
 id bigint generated by default as identity primary key,
 title text not null,
 message text not null,
 priority text not null default 'normal',
 is_public boolean not null default true,
 starts_at timestamptz not null default now(),
 ends_at timestamptz
);
create table if not exists public.media_videos(
 id bigint generated by default as identity primary key,
 title text not null,
 category text not null,
 youtube_url text not null,
 youtube_video_id text,
 description text,
 display_order integer not null default 0,
 is_public boolean not null default true,
 created_at timestamptz not null default now()
);

-- Matches / schedule / score.
create table if not exists public.matches(
 id uuid primary key default gen_random_uuid(),
 match_number integer unique,
 match_date date,
 match_time text,
 team_a_slug text references public.franchises(slug),
 team_a_name text,
 team_b_slug text references public.franchises(slug),
 team_b_name text,
 venue_name text not null default 'Official TNYPL Venue',
 status text not null default 'upcoming',
 live_score text,
 live_overs text,
 live_situation text,
 result_text text,
 scorecard_url text,
 youtube_url text,
 created_at timestamptz not null default now()
);

create table if not exists public.team_standings(
 franchise_slug text primary key references public.franchises(slug),
 team_name text not null,
 played integer not null default 0,
 won integer not null default 0,
 lost integer not null default 0,
 tied integer not null default 0,
 no_result integer not null default 0,
 net_run_rate numeric not null default 0,
 points integer not null default 0,
 updated_at timestamptz not null default now()
);
insert into public.team_standings(franchise_slug,team_name)
select slug,name from public.franchises on conflict(franchise_slug) do nothing;

create table if not exists public.player_tournament_stats(
 player_id text primary key,
 player_name text not null,
 franchise_slug text,
 franchise_name text,
 matches integer not null default 0,
 runs integer not null default 0,
 batting_average numeric not null default 0,
 strike_rate numeric not null default 0,
 highest_score integer not null default 0,
 fours integer not null default 0,
 sixes integer not null default 0,
 wickets integer not null default 0,
 bowling_average numeric not null default 0,
 economy numeric not null default 0,
 best_bowling text,
 catches integer not null default 0,
 mvp_points integer not null default 0,
 updated_at timestamptz not null default now()
);

-- Visitor analytics
create table if not exists public.site_visitors(
 visitor_id text primary key,
 country_code text not null default 'XX',
 country_name text not null default 'Unknown',
 city text,
 first_seen timestamptz not null default now(),
 last_seen timestamptz not null default now()
);
create table if not exists public.site_page_views(
 id bigint generated by default as identity primary key,
 visitor_id text not null,
 page_path text not null default '/',
 country_code text not null default 'XX',
 viewed_at timestamptz not null default now()
);
alter table public.site_visitors enable row level security;
alter table public.site_page_views enable row level security;

create or replace function public.track_site_visit_v12(
 p_visitor_id text,p_country_code text default 'XX',p_country_name text default 'Unknown',p_city text default null,p_page_path text default '/'
) returns void language plpgsql security definer set search_path=public as $$
begin
 insert into public.site_visitors(visitor_id,country_code,country_name,city,first_seen,last_seen)
 values(p_visitor_id,upper(coalesce(nullif(p_country_code,''),'XX')),left(coalesce(nullif(p_country_name,''),'Unknown'),120),left(nullif(p_city,''),120),now(),now())
 on conflict(visitor_id) do update set country_code=excluded.country_code,country_name=excluded.country_name,city=excluded.city,last_seen=now();
 insert into public.site_page_views(visitor_id,page_path,country_code) values(p_visitor_id,left(coalesce(p_page_path,'/'),300),upper(coalesce(nullif(p_country_code,''),'XX')));
end $$;

create or replace function public.get_public_site_stats_v12()
returns jsonb language plpgsql security definer set search_path=public as $$
declare r bigint:=0;v bigint:=0;e bigint:=0;d bigint:=0;rf bigint:=0;
begin
 if to_regclass('public.players') is not null then
  execute 'select count(*) from public.players' into r;
  execute $$select count(*) from public.players where status in ('verified','approved')$$ into v;
  execute $$select count(*) from public.players where draft_status='draft_eligible'$$ into e;
  execute $$select count(*) from public.players where draft_status='drafted'$$ into d;
  execute $$select count(*) from public.players where refund_status='paid'$$ into rf;
 end if;
 return jsonb_build_object(
  'unique_visitors',(select count(*) from public.site_visitors),
  'page_views',(select count(*) from public.site_page_views),
  'countries_reached',(select count(distinct country_code) from public.site_visitors where country_code<>'XX'),
  'online_now',(select count(*) from public.site_visitors where last_seen>=now()-interval '5 minutes'),
  'registrations',r,'verified_players',v,'draft_eligible_players',e,'drafted_players',d,'refunds_processed',rf,
  'countries',coalesce((select jsonb_agg(jsonb_build_object('country_code',country_code,'country_name',country_name,'visitors',visitors) order by visitors desc)
   from(select country_code,max(country_name) country_name,count(*) visitors from public.site_visitors where country_code<>'XX' group by country_code order by count(*) desc limit 10)x),'[]'::jsonb)
 );
end $$;

-- Public read policies for tournament centre.
alter table public.matches enable row level security;
alter table public.team_standings enable row level security;
alter table public.player_tournament_stats enable row level security;
alter table public.league_settings enable row level security;
drop policy if exists "Public read matches" on public.matches;
create policy "Public read matches" on public.matches for select to public using(true);
drop policy if exists "Public read standings" on public.team_standings;
create policy "Public read standings" on public.team_standings for select to public using(true);
drop policy if exists "Public read stats" on public.player_tournament_stats;
create policy "Public read stats" on public.player_tournament_stats for select to public using(true);
drop policy if exists "Public read selected settings" on public.league_settings;
create policy "Public read selected settings" on public.league_settings for select to public using(key in ('league_status','draft_date','tournament_start','tournament_end','live_match_id','live_youtube_url','live_youtube_video_id','youtube_channel_url'));

-- Safe owner-visible player view
create or replace view public.owner_visible_players with(security_invoker=true) as
select id,registration_reference,full_name,district,primary_role,batting_style,bowling_style,academy,cricheroes_url,profile_photo_public_url,draft_category,starting_points,draft_status,drafted_franchise as franchise_slug,created_at
from public.players
where status in ('verified','approved') and draft_status in ('draft_eligible','drafted');

grant select on public.owner_visible_players to authenticated;

select public.get_public_site_stats_v12();
