-- =====================================================================
-- TNYPL V17 OWNER INVITATION ADMIN MIGRATION
-- Run after V16 auction migration.
-- =====================================================================

begin;

create table if not exists public.owner_invites (
  id bigint generated by default as identity primary key,
  owner_user_id uuid references auth.users(id) on delete set null,
  owner_name text not null,
  email text not null,
  franchise_id uuid not null references public.franchises(id) on delete cascade,
  invited_by uuid references auth.users(id) on delete set null,
  invitation_sent boolean not null default false,
  status text not null default 'invited',
  created_at timestamptz not null default now()
);

alter table public.owner_invites enable row level security;

drop policy if exists "admins read owner invites" on public.owner_invites;
create policy "admins read owner invites"
on public.owner_invites
for select
to authenticated
using (public.is_tnypl_admin());

drop policy if exists "service role manages owner invites" on public.owner_invites;
create policy "service role manages owner invites"
on public.owner_invites
for all
to service_role
using (true)
with check (true);

create index if not exists owner_invites_email_idx
  on public.owner_invites(lower(email));

create index if not exists owner_invites_franchise_idx
  on public.owner_invites(franchise_id);

commit;
