begin;
create table if not exists public.site_settings(id integer primary key default 1 check(id=1),registration_deadline timestamptz,registration_open boolean not null default true,show_registration_countdown boolean not null default true,official_timezone text not null default 'Asia/Kolkata',updated_at timestamptz default now());
insert into public.site_settings(id) values(1) on conflict do nothing;
alter table public.site_settings enable row level security;
drop policy if exists "public reads site settings" on public.site_settings;
create policy "public reads site settings" on public.site_settings for select to anon,authenticated using(true);
drop policy if exists "admins manage site settings" on public.site_settings;
create policy "admins manage site settings" on public.site_settings for all to authenticated using(public.is_tnypl_admin()) with check(public.is_tnypl_admin());

alter table public.sponsors add column if not exists logo_path text;
alter table public.sponsors add column if not exists website_url text;
alter table public.sponsors add column if not exists display_order integer not null default 100;
alter table public.sponsors add column if not exists is_active boolean not null default true;
alter table public.sponsors add column if not exists sponsor_level text;
insert into public.sponsors(name,logo_path,website_url,display_order,is_active,sponsor_level) values
('The Cake Point','sponsor-cake-point.png','https://www.cakepoint.in/',10,true,null),
('Ayyappa Auto Agencies','sponsor-ayyappa-auto.png',null,20,true,null),
('DOJO MAN Sports Event App','sponsor-dojo-man.png','https://www.dojoman.com/',30,true,null),
('Vedapile','sponsor-vedapile.png','https://vedapile.com/',40,true,null)
on conflict ((lower(name))) do update set logo_path=excluded.logo_path,website_url=excluded.website_url,display_order=excluded.display_order,is_active=true;

create table if not exists public.admin_team_members(id uuid primary key default gen_random_uuid(),full_name text not null,designation text,department text,biography text,experience text,photo_path text,location text,email text,phone text,display_order integer default 100,is_active boolean default true,is_featured boolean default false,created_at timestamptz default now());


alter table public.admin_team_members enable row level security;
drop policy if exists "public reads active admin team" on public.admin_team_members;
create policy "public reads active admin team" on public.admin_team_members for select to anon,authenticated using(is_active=true or public.is_tnypl_admin());
drop policy if exists "admins manage admin team" on public.admin_team_members;
create policy "admins manage admin team" on public.admin_team_members for all to authenticated using(public.is_tnypl_admin()) with check(public.is_tnypl_admin());

create table if not exists public.tournament_draws(id uuid primary key default gen_random_uuid(),draw_name text not null,status text not null default 'draft',created_by uuid references auth.users(id),created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.tournament_draw_entries(id uuid primary key default gen_random_uuid(),draw_id uuid not null references public.tournament_draws(id) on delete cascade,franchise_id uuid not null references public.franchises(id),group_code text,position_code text,created_at timestamptz default now(),unique(draw_id,franchise_id));
create table if not exists public.tournament_draw_history(id uuid primary key default gen_random_uuid(),draw_id uuid not null references public.tournament_draws(id) on delete cascade,franchise_id uuid not null references public.franchises(id),spin_number integer not null,stage text not null,group_code text,position_code text,random_value numeric,accepted boolean default true,undone boolean default false,created_by uuid references auth.users(id),created_at timestamptz default now());
alter table public.tournament_draws enable row level security;alter table public.tournament_draw_entries enable row level security;alter table public.tournament_draw_history enable row level security;
drop policy if exists "draw read" on public.tournament_draws;create policy "draw read" on public.tournament_draws for select to anon,authenticated using(status in('live','completed','published') or public.is_tnypl_admin());
drop policy if exists "entry read" on public.tournament_draw_entries;create policy "entry read" on public.tournament_draw_entries for select to anon,authenticated using(true);
drop policy if exists "history read" on public.tournament_draw_history;create policy "history read" on public.tournament_draw_history for select to anon,authenticated using(true);
drop policy if exists "draw admin" on public.tournament_draws;create policy "draw admin" on public.tournament_draws for all to authenticated using(public.is_tnypl_admin()) with check(public.is_tnypl_admin());
drop policy if exists "entry admin" on public.tournament_draw_entries;create policy "entry admin" on public.tournament_draw_entries for all to authenticated using(public.is_tnypl_admin()) with check(public.is_tnypl_admin());
drop policy if exists "history admin" on public.tournament_draw_history;create policy "history admin" on public.tournament_draw_history for all to authenticated using(public.is_tnypl_admin()) with check(public.is_tnypl_admin());

create or replace function public.admin_create_tournament_draw(p_draw_name text) returns uuid language plpgsql security definer set search_path=public as $$declare d uuid;c int;begin if not public.is_tnypl_admin() then raise exception 'Admin required';end if;select count(*) into c from public.franchises where is_active=true and name!~*'^Franchise[ ]+[0-9]+$';if c<>8 then raise exception 'Exactly 8 named active franchises required; found %',c;end if;insert into public.tournament_draws(draw_name,created_by) values(coalesce(nullif(trim(p_draw_name),''),'TNYPL Official Draw'),auth.uid()) returning id into d;insert into public.tournament_draw_entries(draw_id,franchise_id) select d,id from public.franchises where is_active=true and name!~*'^Franchise[ ]+[0-9]+$' order by name;return d;end$$;
create or replace function public.admin_lock_tournament_draw(p_draw_id uuid) returns void language plpgsql security definer set search_path=public as $$begin if not public.is_tnypl_admin() then raise exception 'Admin required';end if;update public.tournament_draws set status='live',updated_at=now() where id=p_draw_id;end$$;
create or replace function public.admin_accept_draw_result(p_draw_id uuid,p_franchise_id uuid,p_stage text,p_group_code text,p_position_code text,p_random_value numeric) returns void language plpgsql security definer set search_path=public as $$declare n int;g text;begin if not public.is_tnypl_admin() then raise exception 'Admin required';end if;select group_code into g from public.tournament_draw_entries where draw_id=p_draw_id and franchise_id=p_franchise_id for update;if p_stage='group' then if(select count(*) from public.tournament_draw_entries where draw_id=p_draw_id and group_code=p_group_code)>=4 then raise exception 'Group full';end if;update public.tournament_draw_entries set group_code=p_group_code where draw_id=p_draw_id and franchise_id=p_franchise_id;else if exists(select 1 from public.tournament_draw_entries where draw_id=p_draw_id and position_code=p_position_code) then raise exception 'Position used';end if;update public.tournament_draw_entries set position_code=p_position_code where draw_id=p_draw_id and franchise_id=p_franchise_id;end if;select coalesce(max(spin_number),0)+1 into n from public.tournament_draw_history where draw_id=p_draw_id;insert into public.tournament_draw_history(draw_id,franchise_id,spin_number,stage,group_code,position_code,random_value,created_by) values(p_draw_id,p_franchise_id,n,p_stage,coalesce(p_group_code,g),p_position_code,p_random_value,auth.uid());end$$;
create or replace function public.admin_undo_last_draw_spin(p_draw_id uuid) returns void language plpgsql security definer set search_path=public as $$declare h public.tournament_draw_history;begin select * into h from public.tournament_draw_history where draw_id=p_draw_id and undone=false order by spin_number desc limit 1;if h.stage='group' then update public.tournament_draw_entries set group_code=null,position_code=null where draw_id=p_draw_id and franchise_id=h.franchise_id;else update public.tournament_draw_entries set position_code=null where draw_id=p_draw_id and franchise_id=h.franchise_id;end if;update public.tournament_draw_history set undone=true where id=h.id;end$$;
create or replace function public.admin_reset_tournament_draw(p_draw_id uuid) returns void language plpgsql security definer set search_path=public as $$begin update public.tournament_draw_entries set group_code=null,position_code=null where draw_id=p_draw_id;update public.tournament_draw_history set undone=true where draw_id=p_draw_id;update public.tournament_draws set status='draft' where id=p_draw_id;end$$;
create or replace function public.admin_generate_group_fixtures(p_draw_id uuid,p_start_date date,p_venue text,p_ground text,p_first_time time,p_second_time time) returns integer language plpgsql security definer set search_path=public as $$declare a uuid[];b uuid[];n int:=0;i int;j int;d int;t time;begin select array_agg(franchise_id order by position_code) into a from public.tournament_draw_entries where draw_id=p_draw_id and group_code='A';select array_agg(franchise_id order by position_code) into b from public.tournament_draw_entries where draw_id=p_draw_id and group_code='B';if array_length(a,1)<>4 or array_length(b,1)<>4 then raise exception 'Complete draw first';end if;delete from public.matches where notes='Generated by Official Draw R1';for i in 1..3 loop for j in i+1..4 loop n:=n+1;d:=(n-1)/3;t:=case (n-1)%3 when 0 then p_first_time when 1 then p_second_time else p_second_time+interval '4 hours' end;insert into public.matches(match_number,match_day,match_date,start_time,format,venue,ground,team_a_id,team_b_id,status,is_published,notes) values(n,'Day '||(d+1),p_start_date+d,t,'T20',p_venue,p_ground,a[i],a[j],'scheduled',true,'Generated by Official Draw R1');end loop;end loop;for i in 1..3 loop for j in i+1..4 loop n:=n+1;d:=(n-1)/3;t:=case (n-1)%3 when 0 then p_first_time when 1 then p_second_time else p_second_time+interval '4 hours' end;insert into public.matches(match_number,match_day,match_date,start_time,format,venue,ground,team_a_id,team_b_id,status,is_published,notes) values(n,'Day '||(d+1),p_start_date+d,t,'T20',p_venue,p_ground,b[i],b[j],'scheduled',true,'Generated by Official Draw R1');end loop;end loop;insert into public.matches(match_number,match_day,match_date,start_time,format,venue,ground,status,is_published,result_summary,notes) values(13,'Day 5',p_start_date+4,p_first_time,'T20',p_venue,p_ground,'scheduled',true,'Semi-final 1: A1 vs B2','Generated by Official Draw R1'),(14,'Day 5',p_start_date+4,p_second_time,'T20',p_venue,p_ground,'scheduled',true,'Semi-final 2: B1 vs A2','Generated by Official Draw R1'),(15,'Day 5',p_start_date+4,p_second_time+interval '4 hours','T20',p_venue,p_ground,'scheduled',true,'Final','Generated by Official Draw R1');update public.tournament_draws set status='published' where id=p_draw_id;return 15;end$$;
grant execute on function public.admin_create_tournament_draw(text) to authenticated;grant execute on function public.admin_lock_tournament_draw(uuid) to authenticated;grant execute on function public.admin_accept_draw_result(uuid,uuid,text,text,text,numeric) to authenticated;grant execute on function public.admin_undo_last_draw_spin(uuid) to authenticated;grant execute on function public.admin_reset_tournament_draw(uuid) to authenticated;grant execute on function public.admin_generate_group_fixtures(uuid,date,text,text,time,time) to authenticated;
commit;
select to_regprocedure('public.admin_create_tournament_draw(text)') create_draw_rpc,to_regclass('public.tournament_draws') draws_table,to_regclass('public.site_settings') settings_table;