
begin;

create table if not exists public.franchise_members (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  franchise_id uuid not null references public.franchises(id) on delete cascade,
  full_name text not null,
  email text not null,
  member_role text not null default 'viewer',
  can_bid boolean not null default false,
  can_manage_watchlist boolean not null default false,
  can_manage_players boolean not null default false,
  can_view_settlement boolean not null default false,
  can_manage_members boolean not null default false,
  is_primary_owner boolean not null default false,
  is_active boolean not null default true,
  invited_by uuid references auth.users(id) on delete set null,
  invited_at timestamptz not null default now(),
  accepted_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(user_id, franchise_id)
);

alter table public.franchise_members drop constraint if exists franchise_members_role_check;
alter table public.franchise_members add constraint franchise_members_role_check
check (member_role in ('primary_owner','co_owner','coach','manager','analyst','viewer'));

create table if not exists public.franchise_member_audit (
  id bigint generated by default as identity primary key,
  franchise_id uuid references public.franchises(id) on delete cascade,
  member_user_id uuid references auth.users(id) on delete set null,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  previous_values jsonb,
  new_values jsonb,
  created_at timestamptz not null default now()
);

create index if not exists franchise_members_franchise_idx
on public.franchise_members(franchise_id);

create index if not exists franchise_members_email_idx
on public.franchise_members(lower(email));

create or replace function public.my_franchise_member_id()
returns uuid
language sql stable security definer
set search_path=public
as $$
  select fm.franchise_id
  from public.franchise_members fm
  where fm.user_id=auth.uid() and fm.is_active=true
  order by fm.is_primary_owner desc, fm.invited_at
  limit 1;
$$;

create or replace function public.has_franchise_permission(
  p_franchise_id uuid,
  p_permission text
)
returns boolean
language plpgsql stable security definer
set search_path=public
as $$
declare v public.franchise_members%rowtype;
begin
  if public.is_tnypl_admin() then return true; end if;

  select * into v
  from public.franchise_members
  where user_id=auth.uid()
    and franchise_id=p_franchise_id
    and is_active=true
  limit 1;

  if not found then return false; end if;

  return case p_permission
    when 'bid' then v.can_bid
    when 'watchlist' then v.can_manage_watchlist
    when 'players' then v.can_manage_players
    when 'settlement' then v.can_view_settlement
    when 'members' then v.can_manage_members
    else false
  end;
end;
$$;

insert into public.franchise_members (
  user_id,franchise_id,full_name,email,member_role,
  can_bid,can_manage_watchlist,can_manage_players,
  can_view_settlement,can_manage_members,
  is_primary_owner,is_active,invited_by,accepted_at
)
select
  op.user_id,op.franchise_id,coalesce(op.owner_name,u.email),u.email,
  'primary_owner',true,true,true,true,true,true,
  coalesce(op.is_active,true),op.user_id,now()
from public.owner_profiles op
join auth.users u on u.id=op.user_id
where op.franchise_id is not null
on conflict(user_id,franchise_id) do update set
  full_name=excluded.full_name,
  email=excluded.email,
  member_role='primary_owner',
  can_bid=true,
  can_manage_watchlist=true,
  can_manage_players=true,
  can_view_settlement=true,
  can_manage_members=true,
  is_primary_owner=true,
  is_active=excluded.is_active,
  accepted_at=coalesce(public.franchise_members.accepted_at,now()),
  updated_at=now();

alter table public.franchise_members enable row level security;
alter table public.franchise_member_audit enable row level security;

drop policy if exists "franchise users read team members" on public.franchise_members;
create policy "franchise users read team members"
on public.franchise_members for select to authenticated
using (franchise_id=public.my_franchise_member_id() or public.is_tnypl_admin());

drop policy if exists "service role manages franchise members" on public.franchise_members;
create policy "service role manages franchise members"
on public.franchise_members for all to service_role
using(true) with check(true);

drop policy if exists "franchise managers read member audit" on public.franchise_member_audit;
create policy "franchise managers read member audit"
on public.franchise_member_audit for select to authenticated
using(public.has_franchise_permission(franchise_id,'members') or public.is_tnypl_admin());

drop policy if exists "service role writes member audit" on public.franchise_member_audit;
create policy "service role writes member audit"
on public.franchise_member_audit for all to service_role
using(true) with check(true);

create or replace function public.place_auction_bid(
  p_lot_id uuid,
  p_bid_points integer
)
returns jsonb
language plpgsql security definer
set search_path=public
as $$
declare
  v_uid uuid:=auth.uid();
  v_franchise uuid;
  v_can_bid boolean;
  v_lot public.auction_lots%rowtype;
  v_wallet public.franchise_wallets%rowtype;
  v_current integer;
  v_min integer;
  v_capacity integer;
  v_now timestamptz:=now();
begin
  if v_uid is null then raise exception 'Authentication required'; end if;

  select franchise_id,can_bid into v_franchise,v_can_bid
  from public.franchise_members
  where user_id=v_uid and is_active=true
  order by is_primary_owner desc limit 1;

  if v_franchise is null then raise exception 'Account is not linked to a franchise'; end if;
  if not coalesce(v_can_bid,false) then raise exception 'Your role cannot place bids'; end if;

  select * into v_lot from public.auction_lots where id=p_lot_id for update;
  if not found then raise exception 'Auction lot not found'; end if;
  if v_lot.status<>'open' then raise exception 'Auction is not open'; end if;
  if v_lot.closes_at is not null and v_lot.closes_at<=v_now then
    raise exception 'Bidding time has expired';
  end if;

  select * into v_wallet from public.franchise_wallets
  where franchise_id=v_franchise for update;

  if not found then raise exception 'Franchise wallet not found'; end if;
  if coalesce(v_wallet.is_locked,false) then raise exception 'Franchise is locked'; end if;
  if coalesce(v_wallet.squad_count,0)>=13 then raise exception 'Squad limit reached'; end if;
  if v_lot.highest_franchise_id=v_franchise then
    raise exception 'Your franchise is already highest bidder';
  end if;

  v_current:=coalesce(v_lot.highest_bid,
    v_lot.base_points-public.required_bid_increment(v_lot.base_points));
  v_min:=greatest(v_lot.base_points,
    v_current+public.required_bid_increment(v_current));

  if p_bid_points<v_min then raise exception 'Minimum bid is % points',v_min; end if;

  v_capacity:=coalesce(v_wallet.allocated_points,0)
    +coalesce(v_wallet.credit_limit,0)-coalesce(v_wallet.points_spent,0);

  if p_bid_points>v_capacity then
    raise exception 'Bid exceeds available bidding power of % points',v_capacity;
  end if;

  insert into public.auction_bids(
    lot_id,player_id,franchise_id,owner_user_id,
    bid_points,previous_bid,accepted
  ) values(
    v_lot.id,v_lot.player_id,v_franchise,v_uid,
    p_bid_points,v_lot.highest_bid,true
  );

  update public.auction_lots set
    highest_bid=p_bid_points,
    highest_franchise_id=v_franchise,
    closes_at=case
      when closes_at is null then v_now+interval '45 seconds'
      when closes_at-v_now<interval '10 seconds' then v_now+interval '10 seconds'
      else closes_at end
  where id=v_lot.id;

  return jsonb_build_object(
    'accepted',true,'bid_points',p_bid_points,
    'franchise_id',v_franchise,
    'remaining_capacity',v_capacity-p_bid_points
  );
end;
$$;

grant execute on function public.place_auction_bid(uuid,integer) to authenticated;

commit;
