
-- =====================================================================
-- TNYPL V25 OFFICIAL DRAW CEREMONY
-- Wheel draw, audit log, group/position assignment, and fixture generation.
-- Safe to run repeatedly after V24.
-- =====================================================================

begin;

create table if not exists public.tournament_draws (
  id uuid primary key default gen_random_uuid(),
  draw_name text not null default 'TNYPL Season 1 Official Draw',
  draw_type text not null default 'group_and_position',
  status text not null default 'draft',
  ceremony_mode boolean not null default true,
  current_stage text not null default 'group_a',
  next_group text not null default 'A',
  is_locked boolean not null default false,
  published_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.tournament_draws
  drop constraint if exists tournament_draws_status_check;

alter table public.tournament_draws
  add constraint tournament_draws_status_check
  check (status in ('draft','live','completed','published'));

create table if not exists public.tournament_draw_entries (
  id uuid primary key default gen_random_uuid(),
  draw_id uuid not null references public.tournament_draws(id) on delete cascade,
  franchise_id uuid not null references public.franchises(id) on delete cascade,
  group_code text,
  position_code text,
  draw_order integer,
  is_selected boolean not null default false,
  selected_at timestamptz,
  created_at timestamptz not null default now(),
  unique(draw_id, franchise_id)
);

alter table public.tournament_draw_entries
  drop constraint if exists tournament_draw_entries_group_check;

alter table public.tournament_draw_entries
  add constraint tournament_draw_entries_group_check
  check (group_code is null or group_code in ('A','B'));

alter table public.tournament_draw_entries
  drop constraint if exists tournament_draw_entries_position_check;

alter table public.tournament_draw_entries
  add constraint tournament_draw_entries_position_check
  check (
    position_code is null or
    position_code in ('A1','A2','A3','A4','B1','B2','B3','B4')
  );

create table if not exists public.tournament_draw_history (
  id bigint generated by default as identity primary key,
  draw_id uuid not null references public.tournament_draws(id) on delete cascade,
  spin_number integer not null,
  stage text not null,
  franchise_id uuid references public.franchises(id) on delete set null,
  group_code text,
  position_code text,
  random_value numeric(18,16),
  accepted boolean not null default false,
  undone boolean not null default false,
  actor_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  accepted_at timestamptz,
  undone_at timestamptz
);

create index if not exists draw_entries_draw_idx
  on public.tournament_draw_entries(draw_id, group_code, position_code);

create index if not exists draw_history_draw_idx
  on public.tournament_draw_history(draw_id, spin_number desc);

create or replace function public.touch_tournament_draw_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists tournament_draws_touch on public.tournament_draws;
create trigger tournament_draws_touch
before update on public.tournament_draws
for each row execute function public.touch_tournament_draw_updated_at();

alter table public.tournament_draws enable row level security;
alter table public.tournament_draw_entries enable row level security;
alter table public.tournament_draw_history enable row level security;

drop policy if exists "public reads published draws" on public.tournament_draws;
create policy "public reads published draws"
on public.tournament_draws for select
to anon, authenticated
using (status in ('live','completed','published') or public.is_tnypl_admin());

drop policy if exists "public reads draw entries" on public.tournament_draw_entries;
create policy "public reads draw entries"
on public.tournament_draw_entries for select
to anon, authenticated
using (
  exists (
    select 1 from public.tournament_draws d
    where d.id = tournament_draw_entries.draw_id
      and (d.status in ('live','completed','published') or public.is_tnypl_admin())
  )
);

drop policy if exists "public reads draw history" on public.tournament_draw_history;
create policy "public reads draw history"
on public.tournament_draw_history for select
to anon, authenticated
using (
  accepted = true
  and undone = false
  and exists (
    select 1 from public.tournament_draws d
    where d.id = tournament_draw_history.draw_id
      and (d.status in ('live','completed','published') or public.is_tnypl_admin())
  )
  or public.is_tnypl_admin()
);

drop policy if exists "admins manage draws" on public.tournament_draws;
create policy "admins manage draws"
on public.tournament_draws for all
to authenticated
using (public.is_tnypl_admin())
with check (public.is_tnypl_admin());

drop policy if exists "admins manage draw entries" on public.tournament_draw_entries;
create policy "admins manage draw entries"
on public.tournament_draw_entries for all
to authenticated
using (public.is_tnypl_admin())
with check (public.is_tnypl_admin());

drop policy if exists "admins manage draw history" on public.tournament_draw_history;
create policy "admins manage draw history"
on public.tournament_draw_history for all
to authenticated
using (public.is_tnypl_admin())
with check (public.is_tnypl_admin());

create or replace function public.admin_create_tournament_draw(
  p_draw_name text default 'TNYPL Season 1 Official Draw'
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_draw uuid;
begin
  if not public.is_tnypl_admin() then
    raise exception 'Admin access required';
  end if;

  insert into public.tournament_draws(
    draw_name,status,current_stage,next_group,is_locked,created_by
  )
  values(
    coalesce(nullif(trim(p_draw_name),''),'TNYPL Season 1 Official Draw'),
    'draft','group_a','A',false,auth.uid()
  )
  returning id into v_draw;

  insert into public.tournament_draw_entries(draw_id,franchise_id)
  select v_draw,id
  from public.franchises
  where is_active = true
    and name is not null
    and name !~* '^Franchise[[:space:]]+[0-9]+$'
  order by name
  limit 8;

  return v_draw;
end;
$$;

grant execute on function public.admin_create_tournament_draw(text)
to authenticated;

create or replace function public.admin_lock_tournament_draw(
  p_draw_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  if not public.is_tnypl_admin() then
    raise exception 'Admin access required';
  end if;

  select count(*) into v_count
  from public.tournament_draw_entries
  where draw_id = p_draw_id;

  if v_count <> 8 then
    raise exception 'Exactly 8 active franchises are required. Current count: %', v_count;
  end if;

  update public.tournament_draws
  set is_locked = true,
      status = 'live',
      current_stage = 'group_a',
      next_group = 'A'
  where id = p_draw_id;
end;
$$;

grant execute on function public.admin_lock_tournament_draw(uuid)
to authenticated;

create or replace function public.admin_accept_draw_result(
  p_draw_id uuid,
  p_franchise_id uuid,
  p_stage text,
  p_group_code text default null,
  p_position_code text default null,
  p_random_value numeric default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_spin integer;
  v_entry public.tournament_draw_entries%rowtype;
  v_a integer;
  v_b integer;
begin
  if not public.is_tnypl_admin() then
    raise exception 'Admin access required';
  end if;

  select * into v_entry
  from public.tournament_draw_entries
  where draw_id = p_draw_id
    and franchise_id = p_franchise_id
  for update;

  if not found then
    raise exception 'Franchise is not part of this draw';
  end if;

  if p_stage = 'group' then
    if v_entry.group_code is not null then
      raise exception 'Franchise already has a group';
    end if;

    select count(*) into v_a
    from public.tournament_draw_entries
    where draw_id = p_draw_id and group_code = 'A';

    select count(*) into v_b
    from public.tournament_draw_entries
    where draw_id = p_draw_id and group_code = 'B';

    if p_group_code not in ('A','B') then
      raise exception 'Group must be A or B';
    end if;

    if p_group_code = 'A' and v_a >= 4 then
      raise exception 'Group A is already full';
    end if;

    if p_group_code = 'B' and v_b >= 4 then
      raise exception 'Group B is already full';
    end if;

    update public.tournament_draw_entries
    set group_code = p_group_code,
        is_selected = true,
        selected_at = now()
    where id = v_entry.id;

  elsif p_stage = 'position' then
    if v_entry.group_code is null then
      raise exception 'Assign group before position';
    end if;

    if v_entry.position_code is not null then
      raise exception 'Franchise already has a position';
    end if;

    if p_position_code is null or left(p_position_code,1) <> v_entry.group_code then
      raise exception 'Position must match the assigned group';
    end if;

    if exists (
      select 1 from public.tournament_draw_entries
      where draw_id = p_draw_id
        and position_code = p_position_code
    ) then
      raise exception 'Position % is already assigned', p_position_code;
    end if;

    update public.tournament_draw_entries
    set position_code = p_position_code
    where id = v_entry.id;
  else
    raise exception 'Unsupported draw stage';
  end if;

  select coalesce(max(spin_number),0)+1
  into v_spin
  from public.tournament_draw_history
  where draw_id = p_draw_id;

  insert into public.tournament_draw_history(
    draw_id,spin_number,stage,franchise_id,group_code,position_code,
    random_value,accepted,actor_user_id,accepted_at
  )
  values(
    p_draw_id,v_spin,p_stage,p_franchise_id,p_group_code,p_position_code,
    p_random_value,true,auth.uid(),now()
  );

  return jsonb_build_object(
    'accepted',true,
    'spin_number',v_spin,
    'franchise_id',p_franchise_id,
    'group_code',p_group_code,
    'position_code',p_position_code
  );
end;
$$;

grant execute on function public.admin_accept_draw_result(uuid,uuid,text,text,text,numeric)
to authenticated;

create or replace function public.admin_undo_last_draw_spin(
  p_draw_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_hist public.tournament_draw_history%rowtype;
begin
  if not public.is_tnypl_admin() then
    raise exception 'Admin access required';
  end if;

  select * into v_hist
  from public.tournament_draw_history
  where draw_id = p_draw_id
    and accepted = true
    and undone = false
  order by spin_number desc
  limit 1
  for update;

  if not found then
    raise exception 'No accepted spin to undo';
  end if;

  if v_hist.stage = 'group' then
    update public.tournament_draw_entries
    set group_code = null,
        is_selected = false,
        selected_at = null
    where draw_id = p_draw_id
      and franchise_id = v_hist.franchise_id;
  elsif v_hist.stage = 'position' then
    update public.tournament_draw_entries
    set position_code = null
    where draw_id = p_draw_id
      and franchise_id = v_hist.franchise_id;
  end if;

  update public.tournament_draw_history
  set undone = true,
      undone_at = now()
  where id = v_hist.id;
end;
$$;

grant execute on function public.admin_undo_last_draw_spin(uuid)
to authenticated;

create or replace function public.admin_reset_tournament_draw(
  p_draw_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_tnypl_admin() then
    raise exception 'Admin access required';
  end if;

  delete from public.tournament_draw_history
  where draw_id = p_draw_id;

  update public.tournament_draw_entries
  set group_code = null,
      position_code = null,
      draw_order = null,
      is_selected = false,
      selected_at = null
  where draw_id = p_draw_id;

  update public.tournament_draws
  set status = 'draft',
      current_stage = 'group_a',
      next_group = 'A',
      is_locked = false,
      published_at = null
  where id = p_draw_id;
end;
$$;

grant execute on function public.admin_reset_tournament_draw(uuid)
to authenticated;

create or replace function public.admin_generate_group_fixtures(
  p_draw_id uuid,
  p_start_date date,
  p_venue text,
  p_ground text,
  p_first_time time default '09:00',
  p_second_time time default '13:30'
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  a1 uuid; a2 uuid; a3 uuid; a4 uuid;
  b1 uuid; b2 uuid; b3 uuid; b4 uuid;
  v_count integer := 0;
begin
  if not public.is_tnypl_admin() then
    raise exception 'Admin access required';
  end if;

  select franchise_id into a1 from public.tournament_draw_entries where draw_id=p_draw_id and position_code='A1';
  select franchise_id into a2 from public.tournament_draw_entries where draw_id=p_draw_id and position_code='A2';
  select franchise_id into a3 from public.tournament_draw_entries where draw_id=p_draw_id and position_code='A3';
  select franchise_id into a4 from public.tournament_draw_entries where draw_id=p_draw_id and position_code='A4';
  select franchise_id into b1 from public.tournament_draw_entries where draw_id=p_draw_id and position_code='B1';
  select franchise_id into b2 from public.tournament_draw_entries where draw_id=p_draw_id and position_code='B2';
  select franchise_id into b3 from public.tournament_draw_entries where draw_id=p_draw_id and position_code='B3';
  select franchise_id into b4 from public.tournament_draw_entries where draw_id=p_draw_id and position_code='B4';

  if a1 is null or a2 is null or a3 is null or a4 is null
     or b1 is null or b2 is null or b3 is null or b4 is null then
    raise exception 'All A1-A4 and B1-B4 positions must be assigned';
  end if;

  delete from public.matches
  where notes = 'Generated by TNYPL V25 official draw';

  insert into public.matches(
    match_number,match_day,match_date,start_time,format,venue,ground,
    home_franchise_id,away_franchise_id,status,is_published,notes,created_by
  )
  values
  (1,'Day 1',p_start_date,p_first_time,'T30',p_venue,p_ground,a1,a2,'scheduled',true,'Generated by TNYPL V25 official draw',auth.uid()),
  (2,'Day 1',p_start_date,p_second_time,'T30',p_venue,p_ground,b1,b2,'scheduled',true,'Generated by TNYPL V25 official draw',auth.uid()),
  (3,'Day 2',p_start_date+1,p_first_time,'T30',p_venue,p_ground,a3,a4,'scheduled',true,'Generated by TNYPL V25 official draw',auth.uid()),
  (4,'Day 2',p_start_date+1,p_second_time,'T30',p_venue,p_ground,b3,b4,'scheduled',true,'Generated by TNYPL V25 official draw',auth.uid()),
  (5,'Day 3',p_start_date+2,p_first_time,'T30',p_venue,p_ground,a1,a3,'scheduled',true,'Generated by TNYPL V25 official draw',auth.uid()),
  (6,'Day 3',p_start_date+2,p_second_time,'T30',p_venue,p_ground,b1,b3,'scheduled',true,'Generated by TNYPL V25 official draw',auth.uid()),
  (7,'Day 4',p_start_date+3,p_first_time,'T30',p_venue,p_ground,a2,a4,'scheduled',true,'Generated by TNYPL V25 official draw',auth.uid()),
  (8,'Day 4',p_start_date+3,p_second_time,'T30',p_venue,p_ground,b2,b4,'scheduled',true,'Generated by TNYPL V25 official draw',auth.uid()),
  (9,'Day 5',p_start_date+4,p_first_time,'T30',p_venue,p_ground,a1,a4,'scheduled',true,'Generated by TNYPL V25 official draw',auth.uid()),
  (10,'Day 5',p_start_date+4,p_second_time,'T30',p_venue,p_ground,b1,b4,'scheduled',true,'Generated by TNYPL V25 official draw',auth.uid()),
  (11,'Day 6',p_start_date+5,p_first_time,'T30',p_venue,p_ground,a2,a3,'scheduled',true,'Generated by TNYPL V25 official draw',auth.uid()),
  (12,'Day 6',p_start_date+5,p_second_time,'T30',p_venue,p_ground,b2,b3,'scheduled',true,'Generated by TNYPL V25 official draw',auth.uid()),
  (13,'Semi-final 1',p_start_date+6,p_first_time,'T30',p_venue,p_ground,null,null,'scheduled',true,'Generated by TNYPL V25 official draw · A1 table finisher vs B2 table finisher',auth.uid()),
  (14,'Semi-final 2',p_start_date+6,p_second_time,'T30',p_venue,p_ground,null,null,'scheduled',true,'Generated by TNYPL V25 official draw · B1 table finisher vs A2 table finisher',auth.uid()),
  (15,'Final',p_start_date+7,p_second_time,'T30',p_venue,p_ground,null,null,'scheduled',true,'Generated by TNYPL V25 official draw · Winner SF1 vs Winner SF2',auth.uid());

  get diagnostics v_count = row_count;

  update public.tournament_draws
  set status = 'published',
      current_stage = 'completed',
      published_at = now()
  where id = p_draw_id;

  return v_count;
end;
$$;

grant execute on function public.admin_generate_group_fixtures(uuid,date,text,text,time,time)
to authenticated;

commit;

select
  to_regclass('public.tournament_draws') as draws_table,
  to_regclass('public.tournament_draw_entries') as entries_table,
  to_regclass('public.tournament_draw_history') as history_table;
